### ISSUE TITLE
Hello,Mr，which is the input file in the function public static IfcStore InitIfcModel(string projectName, XbimEditorCredentials credentials, string directory,             string fileName, string bridgeName = "unknown", string bridgeDescription = "unknown") and which is the output file?

### ISSUE THREAD

**Issue by panpan0123** [tumcms/IfcBridgeToolKit#1]

**Comment by seb-esser** [comment]
Dear @panpan0123 , I haven't gotten notified about your issue. Therefore, apologize for responding so late. You do not have to provide any input file to this method as it initializes a new IFC model. 
I just pushed updates to the master - I hope that clarifies things a bit.
